name: Build Model Cache Vault

on: # yamllint disable-line rule:truthy
  push:
    paths:
      - mcv/**
  pull_request:
    paths:
      - mcv/**

jobs:
  build:
    name: Make build (mcv)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgpgme-dev \
            libbtrfs-dev

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
            | sh -s -- -b /usr/local/bin v2.0.2

      - name: Prepare vendored dependencies
        working-directory: mcv
        run: |
          go mod tidy
          go mod vendor

      - name: Run golangci-lint
        working-directory: mcv
        run: |
          GOFLAGS=-mod=vendor golangci-lint run --timeout=5m --modules-download-mode=vendor ./...

      - name: Build with Makefile
        run: make mcv
